import { useState } from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Input from '../modules/form/Input.js'
import Button from '../modules/form/Button.js'
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [n1, setN1] = useState('')
  const [n2, setN2] = useState('')
  const [sun, setSun] = useState('')

  const handleSubmit = (event) => {
    event.preventDefault();
    const resultado = Number(n1) / Number(n2);
    setSun(resultado);
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      
      <div className={styles.card_login}>
        <h1>Você sabe comqual combustivel compensa mais abastecer seu carro?</h1>
        <h2>Utiliza a calculadora abaixo</h2>
        <br />
        <br />
        <div className={styles.CardCalc}>
          <div id="resultado"className={styles.display}>
            {sun < 0.7 && (
              <p>
                Complete with Gasoline
              </p>
            )}
            {sun > 0.7 && (
              <p>
                Complete with Alcool
              </p>
            )}
            {sun == 0.7 && (
              <p>
                Only go
              </p>
            )}
            
          </div>
          <form onSubmit={handleSubmit} className={styles.form}>

            <Input text="Alcohol price" num={n1} setNum={setN1} type='number' placeholder="Write here"/>
           

            <Input text="Gas Price" num={n2} setNum={setN2} type='number' placeholder="Write here"/>

            <Button type="submit" name="calcular"/>
          </form>
          <br />
          <br />
          
          <Image
            src="/img/fuel.webp"
            alt="Descrição da imagem"
            width={150}
            height={90}
            quality={80}
            priority
          />
        </div>

          
          
      

      </div>
    </>
  )
}
